### ISSUE TITLE
Add "reject submission if setup fails" option to AGTestSuite

### ISSUE THREAD

**Issue by james-perretta** [eecs-autograder/autograder-server#526]
- Add new "rejected" status to Submission.GradingStatus, should have similar properties to "removed_from_queue"
    - Bonus submissions used by the rejected submission should be refunded
- Recommend to users that this should only be used in the 1st suite (should we enforce this?)
- Illegal for deferred suites

**Comment by james-perretta** [comment]
What happens when an instructor wants to override this? I.e., what if an instructor decides that a rejected submission should actually be graded? This could happen if there is a mistake in the command that determines whether to reject the submission or for some other unforeseen reason.

@amirkamil @jamesjuett Do you have any thoughts on such a scenario?

**Comment by amirkamil** [comment]
If there is a bug in a regular test case, we would fix it and then rerun the test through the online interface. Maybe something similar for this case? Or a way to rerun all tests on a single submission (which could also be useful if a submission gets stuck)?

**Comment by james-perretta** [comment]
I like that idea. It does make the assumption that false-positive rejections can always be fixed by modifying instructor code or commands, but I think that's a fairly reasonable assumption to make. 

I can rig up a way of doing a full rerun of a single submission. New issue for that can be found here: https://github.com/eecs-autograder/autograder-server/issues/593

**Comment by james-perretta** [comment]
It turns out that the way reruns are currently structured (each suite/submission pair is a task) isn't amenable to rejecting submissions. The solution to this is to re-structure the submission rerun workflow so that is more similar to (and shares code with) regular submission grading. This refactoring will be implemented as part of this issue.
