### ISSUE TITLE
Hand grading not being added to total points in downloaded grades file

### ISSUE THREAD

**Issue by liamoreilly** [eecs-autograder/autograder-server#606]
Hi,

When download grades as a csv file it seems that the Hand Graded Points are not feeding into the Total Points.

Here is a cut and paste from a downloaded csv from the system:

Username | Group Members | Timestamp | Extension | Total Points | Total Points Possible | Handgrading Total Points | Handgrading Total Points Possible | Tests Total | Tests Total Possible | Tests - Test1 | Tests - Test2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Redacted | Redacted | 2020-10-02 13:33:14.463392+00:00 |   | 3 | 4 | 1 | 1 | 3 | 4 | 2 | 1

Notice that Handgrading Total Points is 1 and Test Total Possible is 4. Thus, I would expect Total Points to be 5 (1 + 4). But it is 4.

Similarly with the actual points: Handgrading Total Points is 1 and Test Total is 3, thus I would expect Total Points to be 4 (1 + 3), but it is only 3.

Thus, I am thinking that the handgrading  points are not feeding into the main total.

Any ideas? I hope I am not reading the csv file incorrectly.

**Comment by liamoreilly** [comment]
I had an idea to try to verify my suspicion that the handgrading that is not feeding into the total points.

After adding another Handgrading Checkbox of 5 marks I redownloaded the csv to get:

Username | Group Members | Timestamp | Extension | Total Points | Total Points Possible | Handgrading Total Points | Handgrading Total Points Possible | Tests Total | Tests Total Possible | Tests - Test1 | Tests - Test2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Redacted | Redacted | 2020-10-02 13:33:14.463392+00:00 |   | 3 | 4 | 6 | 6 | 3 | 4 | 2 | 1

This supports my idea that the handgrading that is not feeding into the total points.

**Comment by james-perretta** [comment]
Sorry I missed this--You are correct, and this is actually the intended behavior. The "Total Points" category is for test cases only so that instructors can combine that score with the handgrading score however they wish.

**Comment by liamoreilly** [comment]
Hi,

Thanks @james-perretta for getting back to me - and no worries on time scale :-)
Sorry, if I am being dumb. But if this is the intended behaviour then I think the columns 
"Total Points" and "Test Totals" will always show the same number, as will "Total Points Possible" and "Tests Total Possible". I think this is what adds to my confusion. Please correct me if I am wrong.

To me, the words "Total Points" indicates it is a sum of other columns. While "Tests Total" indicates its the sum of all the tests.

If these pairs of columns really are the same, then maybe removing the "total" versions would make sense.

I am open to a discussion here and just trying to highlight a potential misunderstanding.
Liam

Liam

**Comment by james-perretta** [comment]
Is "Tests" the name of one of your test suites? I think what we might be seeing is that columns to the right of "Handgrading Total Points Possible" include score breakdowns per test suite. So for example if your suite were named "Spam" instead of "Test", the columns in question would be called "Spam Total" and "Spam Total Possible". When there's only one test suite (as in this case), the totals for that test suite will match the overall totals. Does that help clarify things?

**Comment by liamoreilly** [comment]
Oh, very good spot! How did you manage to deduce that? Now it makes complete sense. Sorry for opening the issue.

Liam

**Comment by james-perretta** [comment]
No problem at all! I was trying to find a mention of "Test Total Possible" in the source code, but there wasn't any! Then I noticed that the columns further to the right matched the string interpolation templates used to generate the scores-per-test headers.
