### ISSUE TITLE
Project groups listing route is slow and causes blocking on the student lookup page

### ISSUE THREAD

**Issue by neiljohari** [eecs-autograder/autograder-server#611]
[This route](https://github.com/eecs-autograder/autograder-server/blob/develop/autograder/rest_api/urls.py#L104) is very slow and causes the lookup page to take a long time to load.

For context, I've included a screenshot of the different requests sent during the lookup page. The `/groups` request (last one in the list) took 16 seconds.
![Screen Shot 2020-10-23 at 5 22 06 PM](https://user-images.githubusercontent.com/16354853/97055359-a8e5ca00-1554-11eb-9c2d-05ce2596680f.png)

I'm not familiar enough with Django or this project to confidently propose a solution, but some ideas:
- In this particular context, groups probably don't change very often. A dirty speedup could involve caching the groups every 30 mins.
- We could also cache it indefinitely and simply invalidate it on group creation
- Often, we have the exact uniqname of a student available to us. Perhaps the typeahead isn't necessary (or could be a separate "lookup student" feature)?

Any input would be appreciated. I don't mind taking a shot at implementing something to improve this slowdown!

**Comment by james-perretta** [comment]
Hi there Neil, thanks for opening this! Indeed, this endpoint for 1000 groups is rather slow. I'd like to do some profiling on Monday before exploring other solutions, but I'm happy to post what I find and discuss solutions at that time. My guess is that it has something to do with the submission queries used to figure out things like how many submissions have been used on the current day.

Stay tuned!

**Comment by neiljohari** [comment]
@james-perretta Sounds good, thanks for the quick response! If I have any time to dig deeper, then I'll also update here. 

The main reason I found this was actually while developing an [AG API client tool](https://github.com/neiljohari/claw). 
My current workaround is just to download the groups json once and cache it, hopefully whatever we come up with here makes that unnecessary 😄

**Comment by james-perretta** [comment]
@neiljohari It seems that this endpoint has somehow regressed further since I upgraded to Django 3.1 (this hasn't been deployed yet). It's taking 40s on my local machine and making 1500 DB queries...

**Comment by neiljohari** [comment]
@james-perretta Ah that's not ideal. Did you batch generate groups to stress test it? 

I'm thinking about generating some groups or importing them from 280 prod to have a large sample so I can also debug locally. 

Could this be an N+1 queries problem? It feels like that considering how the # of queries is scaling, but it looks like the call to `prefetch_related` for members and their submissions should've taken care of it. It seems worth making sure it's correct though?

**Comment by james-perretta** [comment]
@neiljohari, Yes, I have some data that I generated with a script for things like this. I'll post the code I used below to do so.

The strange thing to me is that the extra queries are ones that are supposed to be eliminated by prefetch_related (and AFAIK they were before the Django 3.1 upgrade), so I'm going to have to do some investigating there.

Here's the code I used to generate a bunch of groups. I used it a week or two ago, so I'm pretty sure it still works. ; )
```python
# Run this in a Django shell

import random
from django.utils import timezone
from django.contrib.auth.models import User
from autograder.core.models import *
from autograder.core.submission_feedback import update_denormalized_ag_test_results

group_members = []
for i in range(500):
    user = User.objects.get_or_create(username=f'user{i}@autograder.io')[0]
    if i % 2 == 0:
        group_members.append((user,))
    else:
        partner = User.objects.get_or_create(username=f'user{i}_partner@autograder.io')[0]
        group_members.append((user, partner))

p = Project.objects.get(pk=47)
p.max_group_size = 2
p.save()
c = p.course
c.students.set(list(sum((item for item in group_members), tuple())))

cmds = []
for i in range(3):
    suite = AGTestSuite.objects.validate_and_create(project=p, name=f'Suite {i}')
    for i in range(10):
        test_case = AGTestCase.objects.validate_and_create(ag_test_suite=suite, name=f'Test {i}')
        cmd = AGTestCommand.objects.validate_and_create(
            ag_test_case=test_case, 
            name=f'Test {i}',
            cmd='true',
            expected_return_code=ExpectedReturnCode.zero,
            points_for_correct_return_code=1,
        )
        cmds.append(cmd)

mutation_suites = []
for i in range(2):
    suite = MutationTestSuite.objects.validate_and_create(
        project=p, 
        name=f'Mut Suite {i}',
        buggy_impl_names=[f'buggy_impl{i}' for i in range(20)],
        points_per_exposed_bug=1,
    )
    mutation_suites.append(suite)


groups = [
    Group.objects.validate_and_create(project=p, members=members) 
    for members in group_members
]

now = timezone.now()
project_start = now - timezone.timedelta(hours=72)
for group in groups:
    for i in range(random.randint(5, 10)):    
        # Create the submission with "finished status" so it doesn't get graded
        hours_offset = int(random.normalvariate(48, 6))
        # Must be between 0 and 72 hours
        hours_offset = min(hours_offset, 72)
        hours_offset = max(0, hours_offset)
        timestamp = now - timezone.timedelta(hours=hours_offset)
        s = Submission(
            timestamp=timestamp,
            group=group, 
            project=p, 
            status=Submission.GradingStatus.finished_grading
        )
        s.save()
        
        for cmd in cmds:
            test_passes = random.normalvariate(7, 1) > 5
            cmd_result = AGTestCommandResult.objects.validate_and_create(
                return_code=0 if test_passes else 1,
                return_code_correct=test_passes,

                ag_test_command=cmd,
                ag_test_case_result=AGTestCaseResult.objects.get_or_create(
                    ag_test_case=cmd.ag_test_case,
                    ag_test_suite_result=AGTestSuiteResult.objects.get_or_create(
                        ag_test_suite=cmd.ag_test_case.ag_test_suite,
                        submission=s
                    )[0]
                )[0]
            )

        for mut_suite in mutation_suites:
            num_bugs_exposed = int(
                min(random.normalvariate(10, 2), 
                len(mut_suite.buggy_impl_names))
            )
            bugs_exposed = random.choices(mut_suite.buggy_impl_names, k=num_bugs_exposed)
            mut_suite_result = MutationTestSuiteResult.objects.validate_and_create(
                bugs_exposed=bugs_exposed,
                student_tests=[f'test{i}' for i in range(random.randint(0, 15))],
                submission=s,
                mutation_test_suite=mut_suite,
            )

        update_denormalized_ag_test_results(s.pk)
```

**Comment by james-perretta** [comment]
I think I found it: `get_queryset` isn't getting called anymore because of some refactoring I did on my view base classes. The method I have to override now is `get_nested_manager`.

**Comment by james-perretta** [comment]
Fixed and deployed as a hotfix. It should load in ~2 seconds now. Thanks for your feedback and input!

**Comment by neiljohari** [comment]
@james-perretta Awesome thank you so much for the quick response, investigation, and fix into this! 

As a positive side effect, I think this also makes the extensions page much faster since it also hits the `groups/` endpoint. That was my next thing to look into, and I'm pleasantly surprised that this resolves that problem as well 😄

**Comment by james-perretta** [comment]
@neiljohari Yes indeed, the extensions page uses the same endpoint.
